# ====================== JWT Cookies ======================
jwt.refresh-cookie-name=refreshToken
jwt.refresh-cookie-max-age=604800   # 7 ???? ? ????????


# ???????? ??????????? ???? ??????????
springdoc.swagger-ui.operationsSorter=alpha

spring.application.name=backapi

# ====================== SpringDoc Swagger ======================
springdoc.api-docs.path=/v3/api-docs
springdoc.swagger-ui.path=/swagger-ui.html
springdoc.swagger-ui.operations-sorter=method
springdoc.swagger-ui.tags-sorter=alpha

# ====================== DATABASE ======================
spring.datasource.url=jdbc:postgresql://localhost:5432/postgres
spring.datasource.username=postgres
spring.datasource.password=postgres
spring.jpa.hibernate.ddl-auto=update
spring.jpa.show-sql=true

# ====================== JWT ======================
jwt.secret=SuperSecretKeyForJWT2026MakeItAtLeast64CharactersLongForHS512SecurityChangeInProd
jwt.access-expiration=900000
jwt.refresh-expiration=604800000
